# Generated by Django 4.2.7 on 2023-11-14 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='race',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='type',
            new_name='grade',
        ),
        migrations.AddField(
            model_name='character',
            name='precision',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
