# Generated by Django 4.2.7 on 2023-11-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_race_character_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='classe',
            field=models.CharField(choices=[('Stormtrooper', 'Stormtrooper'), ('Death trooper', 'Death trooper'), ('Magma trooper', 'Magma trooper'), ('Night trooper', 'Night trooper'), ('Purge trooper', 'Purge trooper'), ('Sand trooper', 'Sand trooper'), ('Scout trooper', 'Scout trooper'), ('Shoretrooper', 'Shoretrooper'), ('Snowtrooper', 'Snowtrooper'), ('Shock trooper imperial', 'Shock trooper imperial')], max_length=200),
        ),
    ]
