# Generated by Django 4.2.7 on 2023-11-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_character_classe_alter_character_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.CharField(choices=[('https://static.wikia.nocookie.net/frstarwars/images/6/61/Un_Stormtrooper.png/revision/latest?cb=20221112210508', 'https://static.wikia.nocookie.net/frstarwars/images/6/61/Un_Stormtrooper.png/revision/latest?cb=20221112210508'), ('https://static.wikia.nocookie.net/frstarwars/images/c/c3/Death_trooper.png/revision/latest?cb=20161110201800', 'https://static.wikia.nocookie.net/frstarwars/images/c/c3/Death_trooper.png/revision/latest?cb=20161110201800'), ('https://static.wikia.nocookie.net/frstarwars/images/b/b8/Magma_trooper.png/revision/latest?cb=20230729160506', 'https://static.wikia.nocookie.net/frstarwars/images/b/b8/Magma_trooper.png/revision/latest?cb=20230729160506'), ('https://static.wikia.nocookie.net/frstarwars/images/0/04/Soldat_de_la_Nuit.png/revision/latest?cb=20230928080045', 'https://static.wikia.nocookie.net/frstarwars/images/0/04/Soldat_de_la_Nuit.png/revision/latest?cb=20230928080045'), ('https://static.wikia.nocookie.net/frstarwars/images/d/d9/Purge_Trooper_JFO.png/revision/latest?cb=20190414095300', 'https://static.wikia.nocookie.net/frstarwars/images/d/d9/Purge_Trooper_JFO.png/revision/latest?cb=20190414095300'), ('https://static.wikia.nocookie.net/frstarwars/images/7/78/Sandtrooper_DICE.png/revision/latest?cb=20230729160403', 'https://static.wikia.nocookie.net/frstarwars/images/7/78/Sandtrooper_DICE.png/revision/latest?cb=20230729160403'), ('https://static.wikia.nocookie.net/frstarwars/images/7/72/Scout_trooper.png/revision/latest?cb=20230729160529', 'https://static.wikia.nocookie.net/frstarwars/images/7/72/Scout_trooper.png/revision/latest?cb=20230729160529'), ('https://static.wikia.nocookie.net/frstarwars/images/b/bd/Shoretrooper.png/revision/latest?cb=20160930154701', 'https://static.wikia.nocookie.net/frstarwars/images/b/bd/Shoretrooper.png/revision/latest?cb=20160930154701'), ('https://static.wikia.nocookie.net/frstarwars/images/f/f4/Snowtrooper.png/revision/latest?cb=20230729160411', 'https://static.wikia.nocookie.net/frstarwars/images/f/f4/Snowtrooper.png/revision/latest?cb=20230729160411'), ('https://static.wikia.nocookie.net/frstarwars/images/0/09/Shock_trooper_Imp%C3%A9rial.png/revision/latest?cb=20230729160551', 'https://static.wikia.nocookie.net/frstarwars/images/0/09/Shock_trooper_Imp%C3%A9rial.png/revision/latest?cb=20230729160551')], max_length=200),
        ),
    ]
